# Generated by Django 5.0.6 on 2024-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp_app", "0005_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otptoken",
            old_name="tp_created_at",
            new_name="otp_created_at",
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="a05b5a", max_length=6),
        ),
    ]
