# Generated by Django 5.0.6 on 2024-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp_app", "0006_rename_tp_created_at_otptoken_otp_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="661b0e", max_length=6),
        ),
    ]
